### ISSUE TITLE
[chore] Firebase 환경설정

### ISSUE THREAD

**Issue by oceanooooo** [DeveloperAcademy-POSTECH/MacC-Team-AhnNyeong#1]
## 🟣 Description
Firebase 사용을 위한 환경설정을 의미합니다.

## 🟣 Todo

- [x] Bundle Identifier 수정
- [x] GoogleService-Info.plist 추가
- [x] Firebase ios SDK 추가

**Comment by zyeongPark** [comment]
오션머쪄!

**Comment by oceanooooo** [comment]
Bundle Identifier는 com.AhnNyeong.MyMomii로 변경하였습니다.

**Comment by jaelyung** [comment]
스프린트 4 끝나고

- [ ]  firestore dependency 추가
