### ISSUE TITLE
[feat] MVP 대상자 뷰 개발

### ISSUE THREAD

**Issue by jaelyung** [DeveloperAcademy-POSTECH/MacC-Team-AhnNyeong#10]
📣 Assignees와 Labels를 우측에서 추가해 주세요!

## 🟣 Description

- MVP개발에 사용되는 대상자 뷰 개발

## 🟣 Todo

- [x] 생리할 경우 최상단에 있는 생리여부 버튼을 클릭해 생리양, 생리통, 감정 상태를 입력할 수 있는 창을 활성화시킨다
- [x] 생리양, 생리통, 감정 상태를 입력할 수 있는 버튼을 생성한다.
- [x] 생리양, 생리통, 감정 상태를 입력하면 버튼을 눌러 firebase에 저장한다.
