### ISSUE TITLE
[feat] MVP 로그인(유저 분기처리) 뷰 개발

### ISSUE THREAD

**Issue by oceanooooo** [DeveloperAcademy-POSTECH/MacC-Team-AhnNyeong#11]
📣 Assignees와 Labels를 우측에서 추가해 주세요!

## 🟣 Description

<img width="298" alt="image" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-AhnNyeong/assets/127754551/1dcbd11f-a944-4baa-9d75-114a33b62f13">
- 선택하는 버튼에 따라 진입할 수 있는 화면 및 기능이 다릅니다.
- [관리자 접속] 버튼 선택 시 관리자 메인 화면으로 이동합니다.
- [대상자 접속] 버튼 선택 시 대상자 메인 화면으로 이동합니다.

## 🟣 Todo

- [x] 뷰 깎기
- [x] 관리자 대상자 분기처리

## 🟣 ETC

- 다른 화면 머지 후 분기처리 관련 코드 추가 필요

**Comment by oceanooooo** [comment]
- [ ] 관리자 화면에서 로그인 화면으로 돌아가는 버튼 추가
- [ ] 대상자 화면에서 로그인 화면으로 돌아가는 버튼 추가

**Comment by oceanooooo** [comment]
MVP 구현 완료
