### ISSUE TITLE
[feat] MVP 관리자의 대상자 정보 조회 뷰 개발 

### ISSUE THREAD

**Issue by zyeongPark** [DeveloperAcademy-POSTECH/MacC-Team-AhnNyeong#12]
📣 Assignees와 Labels를 우측에서 추가해 주세요!

## 🟣 Description

MVP 개발 중, 관리자가 대상자의 3가지 생리 정보를 날짜 별로 확인할 수 있는 뷰를 구현합니다. 

## 🟣 Todo

- [x] 스크롤뷰로 이루어져 있습니다. 
- [x] 년,월,일의 날짜 정보를 받아오고 생리 정보뷰의 가장 처음에 한 번 나올 수 있게 합니다. 
- [x] 관리자가 대상자의 생리 정보를 받아온 후 string 값으로 보여지게 합니다. 
- [x] 하루에 여러 개의 정보가 들어올 경우, 아래로 계속해서 쌓일 수 있도록 합니다.

**Comment by zyeongPark** [comment]
MVP 기능 완료
