### ISSUE TITLE
[feat] 관리자 캘린더 뷰 UI 유연 구현

### ISSUE THREAD

**Issue by oceanooooo** [DeveloperAcademy-POSTECH/MacC-Team-AhnNyeong#23]
📣 Assignees와 Labels를 우측에서 추가해 주세요!

## 🟣 Description
- 관리자 캘린더 뷰의 UI를 구현합니다.
- 똑같은 형태로 완벽히 개발하는 것이 아닌 얼마든지 자유자재로 이용 및 변형이 가능하도록 구현합니다.
- 좌/우 스와이프로 이전/다음 달로 이동할 수 있습니다.
- 현재 달의 이벤트(생리주기)를 라인형으로 구현합니다.
- 알림의 숫자를 아이콘 뱃지로 구현합니다.

<img width="200" alt="image" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-AhnNyeong/assets/127754551/0f51b55a-822e-4459-89ce-ef07fd3c77f4">

## 🟣 Todo

- [ ] 달력 UI 구현
- [ ] 일정(주기) 구현
- [ ] 알림 아이콘 뱃지 구현

## 🟣 ETC

- 투비퍼펙트제이의 ezcal을 참고
- 대상자 캘린더에서도 사용할 수 있음을 염두에 둘 것
