### ISSUE TITLE
[feat] 대상자 첫화면 UI

### ISSUE THREAD

**Issue by jaelyung** [DeveloperAcademy-POSTECH/MacC-Team-AhnNyeong#24]
📣 Assignees와 Labels를 우측에서 추가해 주세요!

## 🟣 Description

기능을 제외한 화면 UI 를 그립니다

## 🟣 Todo

- [x] 대상자 진입 뷰
- [x] 관리자 메인 알림 이력 조회 뷰
- [x] 관리자 입력 이력 조회 뷰
- [x] 관리자 대상자 상세조회

**Comment by jaelyung** [comment]
- 중복 코드 모듈화하기
- Layout 코드 다듬기
