### ISSUE TITLE
[feat] 관리자의 대상자 카드 입력 뷰 구현

### ISSUE THREAD

**Issue by zyeongPark** [DeveloperAcademy-POSTECH/MacC-Team-AhnNyeong#25]
📣 Assignees와 Labels를 우측에서 추가해 주세요!

## 🟣 Description

관리자가 대상자의 카드를 생성하는 뷰의 레이아웃을 구현합니다. 

## 🟣 Todo

- [ ] 뷰 최상단에 chevron 이미지 구현 
- [ ] 그 아래에 Text 구현
- [ ] 뷰 중간에, 이름과 전화번호 입력 받는 custom된 Textfield 구현
- [ ] 뷰 최하단에 초대하기 버튼 구현
