### ISSUE TITLE
[feat] 이용자 시작화면 TargetMainView 생성

### ISSUE THREAD

**Issue by jaelyung** [DeveloperAcademy-POSTECH/MacC-Team-AhnNyeong#29]
📣 Assignees와 Labels를 우측에서 추가해 주세요!

## 🟣 Description

이용자가 앱에 접속했을때 볼 수 있는 가장 첫번째 화면을 그립니다.

## 🟣 Todo

- [x] 가운데 물방울 버튼 클릭
- [x] 앱 실행시 파티클 효과
- [x] 클릭시 멘트변경
- [x] 달력보기 버튼 생성
