### ISSUE TITLE
[feat] HiFi가 적용된 LogInView의 모든 레이아웃을 구현합니다. 

### ISSUE THREAD

**Issue by zyeongPark** [DeveloperAcademy-POSTECH/MacC-Team-AhnNyeong#34]
📣 Assignees와 Labels를 우측에서 추가해 주세요!

## 🟣 Description

 HiFi가 적용된 LogInView의 모든 레이아웃을 구현하고, 뷰가 넘어가는 흐름까지만 구현합니다. 

## 🟣 Todo

- [ ] OnboardingView 레이아웃구현
- [ ] LoginView 레이아웃 구현 
- [ ] StartRegiView 레이아웃 구현
- [ ] MngRegiView 레이아웃 구현
- [ ] TargetRegiView 레이아웃 구현
- [ ] TargetRegiWithCodeView 레이아웃 구현
- [ ] TermView 레이아웃 구현 
- [ ] MngRegiCompView 레이아웃 구현
- [ ] TargetRegiCompView 레이아웃 구현

## 🟣 ETC

뷰의 흐름 상 어색한 부분이 있다면 말씀해주세요 ~
