### ISSUE TITLE
[feat] 메인 설정 화면 구현

### ISSUE THREAD

**Issue by oceanooooo** [DeveloperAcademy-POSTECH/MacC-Team-AhnNyeong#36]
📣 Assignees와 Labels를 우측에서 추가해 주세요!

## 🟣 Description

- 대상자의 이름을 보여줍니다.
- 로그인 타입(대상자/관리자)에 맞는 소속 라벨을 보여줍니다.
- [로그아웃], [계정삭제]를 누를 경우 알맞는 alert를 보여줍니다.

<img width="200" alt="image" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-AhnNyeong/assets/127754551/db56f557-c967-44be-820e-63f1a465e282">
<img width="200" alt="image" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-AhnNyeong/assets/127754551/8ab4becd-e5d4-42f1-838c-0be99380fc42">
<img width="200" alt="image" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-AhnNyeong/assets/127754551/b40bf843-850d-4ccd-97aa-d083b307eb08">
<img width="200" alt="image" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-AhnNyeong/assets/127754551/6fa09631-43dc-4d69-ad05-83efc743dafa">

## 🟣 Todo

- [x] 로그인 타입에 맞는 라벨 출력
- [x] 내비게이션 리스트 구현
- [x] alert 구현
- [x] [로그아웃] 선택 시 로그인 타입 초기화(.notyet)
- [x] 에셋 적용

## 🟣 ETC

- List로 구현할 경우 UI/UX적 제한 요소가 많아 커스텀 개발했습니다. -> SettingList, ListTitle
- List가 아니기 때문에 Divider()를 사용하려 했으나 색상 및 두께 변경이 되지 않아 커스텀 개발했습니다. -> DividingRectangle
