### ISSUE TITLE
[feat] 달력에 시각적 표현

### ISSUE THREAD

**Issue by oceanooooo** [DeveloperAcademy-POSTECH/MacC-Team-AhnNyeong#4]
## 🟣 Description
생리 기록이 있을 경우 월간 달력에 표시하는 화면입니다.
생리 중일 경우 해당 날짜의 칸은 컬러링이 됩니다.
생리에 대한 상세기록이 있을 경우 해달 날짜의 칸에 작은 점이 표시됩니다.
달력은 좌로 스와이프 할 경우 이전달, 우로 스와이프 할 경우 다음달로 이동합니다.
하단에 생리 기록 상세 화면으로 이동하기 위한 버튼이 있습니다.
<img width="228" alt="image" src="https://github.com/DeveloperAcademy-POSTECH/MacC-Team-AhnNyeong/assets/127754551/a8d99d3f-ed62-4a8e-899e-60ea472ce916">

## 🟣 Todo

- [x] 월간 달력 생성
- [x] 가로 스와이프로 이전달/다음달 이동
- [x] 오늘 날짜 표시
- [ ] 생리 입력 화면으로 이동하는 버튼 생성
- [x] 생리 기록 있을 경우 칸 컬러링
- [x] 생리 증상 상세 기록 있을 경우 도트 표시

## 🟣 ETC

- 다음 단계에서 디자인적 요소 반영

**Comment by oceanooooo** [comment]
Hi-Fi 적용으로 인해 불필요
