### ISSUE TITLE
[feat] 이용자 증상 입력 View 구현

### ISSUE THREAD

**Issue by jaelyung** [DeveloperAcademy-POSTECH/MacC-Team-AhnNyeong#40]
📣 Assignees와 Labels를 우측에서 추가해 주세요!

## 🟣 Description

이용자가 증상 3가지(배가 아파요, 생리양, 나의 기분)을 입력하는 View를 구현합니다.

## 🟣 Todo

- [x] 화면 최상단 날짜
- [x] Asset 교체
- [x] 증상 선택시 Stroke 이미지 출력
- [x] 이미지 하단 텍스트 추가
- [x] 증상 선택시 텍스트 색상 변경
