### ISSUE TITLE
[feat] 관리자 메인화면 구현

### ISSUE THREAD

**Issue by jaelyung** [DeveloperAcademy-POSTECH/MacC-Team-AhnNyeong#48]
📣 Assignees와 Labels를 우측에서 추가해 주세요!

## 🟣 Description

관리자 메인화면인 생리현황 조회 페이지를 구현합니다.

## 🟣 Todo

- [ ] 연도, 날짜
- [ ] 오늘 생리중 컴포넌트 생성
- [ ] 곧 생리 예정 컴포넌트
- [ ] 알람 아이콘 표시 -> 숫자 카운트 오션
- [ ] 설정페이지 기어 버튼
- [ ] 탭바 적용

**Comment by jaelyung** [comment]
생리 시작 지연 알림 .alert 코드는 삽입했으나 로직이 없음
