### ISSUE TITLE
[fix] Sprint7 피드백 반영

### ISSUE THREAD

**Issue by jaelyung** [DeveloperAcademy-POSTECH/MacC-Team-AhnNyeong#52]
📣 Assignees와 Labels를 우측에서 추가해 주세요!

## 🟣 Description

Sprint7에서 받은 피드백 및 발견한 버그들을 수정합니다.

## 🟣 Todo

- [x] LottieView 때문에 버튼이 안눌리는 현상 수정
- [x] iPhone13mini 또는 SE 기준 크기로 증상입력뷰 수정
- [x] 관리자 상단 툴바 배경색
