### ISSUE TITLE
[feat] 대상자 View Mid-fi 반영

### ISSUE THREAD

**Issue by jaelyung** [DeveloperAcademy-POSTECH/MacC-Team-AhnNyeong#7]
📣 Assignees와 Labels를 우측에서 추가해 주세요!

## 🟣 Description

대상자 View 화면디자인과 Flow을 Mid-fi로 변경합니다.

## 🟣 Todo

- [x] 생리주기 및 증상 입력 View 디자인 반영
- [x] 캘린더 뷰와 생리주기 및 증상 입력 뷰 연결
- [x] 대상자 메인 뷰 Flow 수정
