### ISSUE TITLE
[feat] 담당하는 대상자들 정보 대쉬보드 - 관리자

### ISSUE THREAD

**Issue by zyeongPark** [DeveloperAcademy-POSTECH/MacC-Team-AhnNyeong#8]
📣 Assignees와 Labels를 우측에서 추가해 주세요!

## 🟣 Description

메인 뷰의 탭 바를 구현하고, 하단 탭 중 "리스트"에 해당하는 뷰만 구현합니다. 
- 관리자 페이지에서 대상자들의 정보를 카드뷰 형식으로 보여줄 수 있도록 하고, "+" 버튼을 입력하면 대상자를 추가할 수 있도록 합니다. 

## 🟣 Todo

- [ ] 하단 탭 바 형식으로 전체 뷰 구성 
- [ ] 카드뷰 형식의 대상자 List 뷰 구현
- [ ] 우측 상단의 + 버튼 클릭 시, 대상자의 정보를 입력하는 페이지로 넘어가도록 구성
- [ ] 대상자 정보 입력 완료 시 이름과 개별로 필요한 정보가 관리자_대상자_리스트 조회 뷰에서 나타날 수 있도록 구현 

## 🟣 ETC

- 변경된 midFi 디자인에 따라 새롭게 뷰 구성합니다. 
- 현재, 카테고리 기능은 구현하지 않았습니다.
-  대상자의 정보를 firebase에 저장하지 않고, 앱 내부에 저장하도록 구성하였습니다. -> 확인 필요
